[package]
name = "goods-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
goods-application = { path = "../goods-application" }
goods-domain = { path = "../goods-domain" }
goods-infrastructure = { path = "../goods-infrastructure" }

[lints.rust]
unsafe_code = "forbid"
